Misc classification typing
brainglobe/cellfinder-core pull request #106
Opened 2023-03-28 08:51 UTC by dstansby

While I was looking at the `tensorflow` issue, I started typing some of the classification code. This is very incomplete, but since I don't intend to come back to it in the near future, I figured it's worth adding what I did instaed of losing it.

2023-03-28 13:40 UTC, dstansby commented on src/cellfinder_core/classify/classify.py
> +    signal_array: np.ndarray,
I've created a new `types.py` file to have an array-like type - open to other options but I think that's one way to go.

2023-03-29 10:06 UTC, adamltyson requested changes

2023-03-29 10:06 UTC, adamltyson commented on src/cellfinder_core/classify/cube_generator.py
> +        background_array: np.ndarray,
```suggestion
        background_array: types.array,
```

2023-03-30 15:39 UTC, adamltyson approved these changes

2023-03-30 15:39 UTC, merged