Limit number of 2D filtering outputs stored in memory
brainglobe/cellfinder-core pull request #139
Opened 2023-04-05 14:39 UTC by dstansby

After running into a bit of a dead end on `dask` (see https://github.com/brainglobe/cellfinder-core/issues/118#issuecomment-1497513776 for more info), I had a re-think and brainwave on how to solve https://github.com/brainglobe/cellfinder-core/issues/73 and might have come up with a plan...

The idea is to create a lock for each plane in the input data, and only release the lock for plane `n` when planes `n - ball_z_size - 1` to `n - 1` start being filtered by the 3D filter. This replicates the behaviour before version 0.3.0, and might solve https://github.com/brainglobe/cellfinder-core/issues/73

2023-04-18 12:53 UTC, adamltyson commented
Seems like a good idea, but #145 is preventing me from testing it properly.

2023-04-28 09:02 UTC, alessandrofelder requested changes
I found a small edge case that needs guarding against, otherwise looks good.

I ran into issues with real-life data and was about to open #149 and #158 when I realised someone had already :facepalm: 

I found an issue #159 with numba further down the line from #158 that we can tackle separately.

If I pass a slice of real-life data that does not require splitting the result looks sensible to me.

2023-04-28 13:17 UTC, dstansby commented on src/cellfinder_core/detect/detect.py
> +def _map_with_locks(
I've added a basic test, but couldn't come up with anything much more than your suggestion

2023-04-28 13:17 UTC, dstansby commented on src/cellfinder_core/detect/detect.py
> +        for i in range(n_ball_procs + ball_z_size):
It does indeed fix it, and I've added a test 👍

2023-04-28 13:22 UTC, dstansby commented on src/cellfinder_core/detect/detect.py
> +from threading import Lock
[`multiprocessing.Manager.Lock()`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.managers.SyncManager.Lock) returns `threading.Lock()` instance, so I think this has to stay as is.

2023-04-28 14:14 UTC, alessandrofelder approved these changes
Cool!

2023-04-28 14:14 UTC, merged